"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

format = """
[▐](fg:color_aqua)\
$username\
[](bg:color_blue fg:color_aqua)\
$directory\
[](fg:color_blue bg:color_purple)\
$git_branch\
$git_status\
[](fg:color_purple bg:color_bg2)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_bg2 bg:color_bg)\
\n$character
"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_bg0 = '#fbf1c7'
color_fg1 = '#ebdbb2'
color_bg = '#282828'
color_bg2 = '#504945'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[username]
show_always = true
style_user = "bg:color_aqua fg:color_bg0"
style_root = "bg:color_orange fg:color_bg0"
format = '[$user ]($style)'

[directory]
style = "fg:color_bg0 bg:color_blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Pictures" = "󰋩 "
".dotfiles" = " "
"~/.config" = "~/ "

[git_branch]
symbol = ""
style = "bg:color_purple"
format = '[[ $symbol $branch ](fg:color_bg0 bg:color_purple)]($style)'

[git_status]
style = "bg:color_purple"
format = '[[($all_status$ahead_behind )](fg:color_bg0 bg:color_purple)]($style)'

[nodejs]
symbol = ""
style = "bg:color_bg2"
format = '[[ $symbol($version) ](fg:color_fg1 bg:color_bg2)]($style)'

[c]
symbol = " "
style = "bg:color_bg2"
format = '[[ $symbol($version) ](fg:color_fg1 bg:color_bg2)]($style)'

[rust]
symbol = ""
style = "bg:color_bg2"
format = '[[ $symbol($version) ](fg:color_fg1 bg:color_bg2)]($style)'

[golang]
symbol = ""
style = "bg:color_bg2"
format = '[[ $symbol($version) ](fg:color_fg1 bg:color_bg2)]($style)'

[php]
symbol = ""
style = "bg:color_bg2"
format = '[[ $symbol($version) ](fg:color_fg1 bg:color_bg2)]($style)'

[java]
symbol = " "
style = "bg:color_bg2"
format = '[[ $symbol($version) ](fg:color_fg1 bg:color_bg2)]($style)'

[kotlin]
symbol = ""
style = "bg:color_bg2"
format = '[[ $symbol($version) ](fg:color_fg1 bg:color_bg2)]($style)'

[haskell]
symbol = ""
style = "bg:color_bg2"
format = '[[ $symbol($version) ](fg:color_fg1 bg:color_bg2)]($style)'

[python]
symbol = ""
style = "bg:color_bg2"
format = '[[ $symbol($version) ](fg:color_fg1 bg:color_bg2)]($style)'

[character]
disabled = false
success_symbol = '[ ](fg:color_green)'
error_symbol = '[ ](fg:color_red)'
vimcmd_symbol = '[ ](fg:color_purple)'
