Section "InputClass"
  Identifier "libinput touchpad"
  MatchIsTouchpad "on"
  Driver "libinput"
  Option "Tapping" "on"
  Option "NaturalScrolling" "on"
  Option "ScrollMethod" "twofinger"
EndSection

Section "InputClass"
  Identifier "libinput all pointers"
  MatchIsPointer "on"
  Option "AccelProfile" "flat"
EndSection
